---
title: "Datos de felinos de Costa Rica"
author: "Sofía Carpio"
date: '2022-06-08'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preparativos 
```{r carga-paquetes, message=FALSE}
library (ddplyr)
library(ggplot2)
library(plotly)
library(sf)
library(DT)
library(leaflet)
```

```{r}
# Lectura de un archivo CSV con registros de presencia de felinos en Costa Rica
felinos <-
  st_read(
    "felinos.csv",
    options = c(
      "X_POSSIBLE_NAMES=decimalLongitude", # columna de longitud decimal
      "Y_POSSIBLE_NAMES=decimalLatitude"   # columna de latitud decimal
    ),
    quiet = TRUE
  )
```


# Tabla 
```{r tabla, echo=FALSE}
# visualización de datos de felinos en formato tabular 
felinos %>% 
dplyr::select(species, 
              eventDate, 
              stateProvince, 
              locality, 
              decimalLongitude,
              decimalLatitude) %>% 
  st_drop_geometry() %>% 
  datatable(colnames = c(
    "Especie", 
    "Fechas", 
    "Provincia",
    "Localidad", 
    "Longitud", 
    "Latitud"
    ),
    options = list(
    pageLength = 10, 
    languaje = list(url = '//cdn.datatables.net/plus-ins/1.10.11/i18n/Spanish.json')
  ))
```


# Gráfico 
```{r grafico, message=FALSE, echo=FALSE}
geafico_barras <-
  felinos %>%
  ggplot(aes(x = species)) +
  geom_bar() 

ggplotly(grafico_barras)
```


# Mapa 
```{r mapa, message=FALSE, echo=FALSE}
# Mapa leaflet básico con capas de altitud, provincias y registros de presencia de felinos
leaflet() %>%
  addTiles() %>%
  addCircleMarkers(
    data = felinos,
    stroke = F,
    radius = 4,
    fillColor = 'blue',
    fillOpacity = 1
  )
```


# profe 
https://github.com/mfvargas/felinos
 
 

